#!/bin/sh
POSTGRES_DATABASE_URI="postgres+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_DATABASE_PASSWORD}@${POSTGRES_HOSTNAME:-postgresql}:${POSTGRES_PORT:-5432}/${POSTGRES_DATABASE:-postgres}"
export POSTGRES_DATABASE_URI
